version: '3.3'

services:
  db:
    image: mysql:5.7
    command: --innodb-log-file-size=500M --innodb_strict_mode=0
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root

  dev:
    depends_on:
      - db
    image: rapporteket/ablanor-dev:nightly
    volumes:
      - ~/.ssh:/home/rstudio/.ssh
      - ~/.gitconfig:/home/rstudio/.gitconfig
      - config:/home/rstudio/rap_config
    ports:
      - "8787:8787"
      - "3838:3838"
    dns:
      - 8.8.8.8
    restart: "no"
    environment:
      USERID: $USERID
      PASSWORD: password
      DB_HOST: db
      DB_USER: root
      DB_PASS: root

  app:
    depends_on:
      - dev
    image: rapporteket/ablanor:poc
    volumes:
      - config:/app/R
    ports:
      - "3008:3838"
    restart: "no"
    environment:
      R_RAP_CONFIG_PATH: /app/R
      R_RAP_INSTANCE: QAC
      USERFULLNAME: Tore Tester Container
      SHINYPROXY_USERNAME: ttesterc
      SHINYPROXY_USERGROUPS: "LC,LC,SC,LC"
      USERORGID: "[1, 2, 3, 4]"
      USEREMAIL: ttesterc@holigong.no
  
  rapadm:
    depends_on:
      - dev
    image: rapporteket/rapadm:main
    volumes:
      - config:/app/R
    ports:
      - "3088:3838"
    restart: "no"
    environment:
      R_RAP_CONFIG_PATH: /app/R
      R_RAP_INSTANCE: QAC
      USERFULLNAME: Tore Tester Container
      SHINYPROXY_USERNAME: ttesterc
      SHINYPROXY_USERGROUPS: "LC,LC,SC,LC,SC,SC"
      USERORGID: "[1, 2, 3, 4, 5, 6]"
      USEREMAIL: ttesterc@holigong.no
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8

  adminer:
    depends_on:
      - db
    image: adminer
    restart: "no"
    environment:
      ADMINER_PLUGINS: frames
    ports:
      - 8888:8080

volumes:
  config:
