
Sys.setenv(FALK_EXTENDED_USER_RIGHTS="[{\"A\":80,\"R\":\"SC\",\"U\":4219765},{\"A\":80,\"R\":\"LU\",\"U\":4219765},{\"A\":80,\"R\":\"LC\",\"U\":4219765},{\"A\":80,\"R\":\"LC\",\"U\":700328}]")
Sys.setenv(MYSQL_DB_LOG="db_log")
Sys.setenv(MYSQL_DB_AUTOREPORT="db_autoreport")
Sys.setenv(MYSQL_DB_DATA="ablanor")
Sys.setenv(MYSQL_HOST="localhost")
Sys.setenv(MYSQL_USER="root")
Sys.setenv(MYSQL_PASSWORD="root")
Sys.setenv(FALK_APP_ID="80")
Sys.setenv(FALK_USER_EMAIL="jesus@sky.no")
Sys.setenv(FALK_USER_FULLNAME="Arnie")
Sys.setenv(USERORGID="pilot")
Sys.setenv(SHINYPROXY_USERNAME="skkris")
Sys.setenv(SHINYPROXY_USERGROUPS="pilot")
Sys.setenv(SHINYPROXY_APPID="80")
Sys.setenv(R_RAP_INSTANCE="QAC")
Sys.setenv(R_RAP_CONFIG_PATH=paste0(getwd(), "/dev/config"))
