
Sys.setenv(FALK_EXTENDED_USER_RIGHTS="[{\"A\":80,\"R\":\"LC\",\"U\":102966},{\"A\":80,\"R\":\"SC\",\"U\":102966},{\"A\":80,\"R\":\"LC\",\"U\":700328}]")
Sys.setenv(MYSQL_DB_LOG="db_log")
Sys.setenv(MYSQL_DB_AUTOREPORT="db_autoreport2")
Sys.setenv(MYSQL_DB_DATA="AblanorRapporteket")
Sys.setenv(MYSQL_HOST="db")
Sys.setenv(MYSQL_USER="root")
Sys.setenv(MYSQL_PASSWORD="root")
Sys.setenv(FALK_APP_ID="80")
Sys.setenv(USERORGID="pilot")
Sys.setenv(SHINYPROXY_USERNAME="sivh")
Sys.setenv(SHINYPROXY_USERGROUPS="pilot")
Sys.setenv(R_RAP_INSTANCE="QAC")
Sys.setenv(R_RAP_CONFIG_PATH="dev/config")
