---
title: Veiledning eksport av data
---

## Eksport av databasen til AblaNor
Her kan statistikere som jobber med Rapporteket for Ablanor laste ned hele databasen. Formatet som benyttes gjør det enkelt å sette opp en engen database for utviklingsformål. Nedlastet fil er kryptert og innholdet er utilgjenglig for alle andre enn definert mottaker. Filen slik den lastes ned kan derfor trygt transporteres og eksponeres offentlig uten fare for at innholdet (registerdata) blir tilgjenglig for andre.

## Veiledning
Under følger en kort veiledning for trygg og riktig bruk av eksportfunksjonen.

### Last ned og lagre fila
Velg mottaker fra lista til venstre. For den valgte mottakeren vil det da være mulig å angi hvilken offentlig nøkkel som skal benyttes i krypteringen av innholdet. Det er en forutsetning at mottakeren av nedlastet fil har en brukerkonto på GitHub og at vedkommende har lagt ut minst én offentlig nøkkel der. Videre må denner brukeren også ha fått tilgang til registerets prosjekt i organisasjonen [Rapporteket på GitHub](https://github.com/Rapporteket). Ved spørsmål eller behov for hjelp, ta kontakt med [SKDE](mailto:rapporteket@helse-nord.no).

### Dekryptering av innholdet i fila
Fila slik den er lastet ned er sikret mot innsyn fra andre enn definert mottaker. Etter dekryptering vil denne sikringen ikke lengre eksistere og det er derfor viktig at dekryptering kun skjer i et område som har en ytre sikring, eksempelvis en datamaskin og et filområde på et sykehus som er godkjent for bruk til helse- og personopplysninger.
[R-pakken `sship`](https://github.com/Rapporteket/sship/) kan enkelt benyttes til dekryptering, eksempelvis:

```{r decrypt, eval=FALSE}
library(sship)<br>
dec(tarfile = "dump.sql__20200101_081500.tar.gz",
    keyfile = "~/.ssh/id_rsa",
    target_dir = ".")
```

Det finnes også andre måter å dekryptere fila på. Mer om dette og øvrige detaljer kan leses i [dokumentasjonen av `sship`](https://rapporteket.github.io/sship/articles/extract.html).

### Import av databasen
Eksportfila er etablert ved en konvensjonell eksport av data fra en databasemotoren [MySQL](https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html) og det finnes derfor flust av beskrivelser for import. Når man benytter utviklingsmiljø definert av SKDE for bruk i forbindelse med Rapporteket kan eksportfila importeres gjennom [importfunksjonen som finnes i verktøyet adminer](http://localhost:8888/?server=db&username=root&db=ablanor&import=).

## Sikkerhet
Sikringen av data slik de lastes ned her er ivaretatt av [R-pakken `sship`](https://github.com/Rapporteket/sship/) i kombinasjon med samhandlingsverktøyet [Rapporteket på GitHub](https://github.com/Rapporteket). Mer detaljer om dette kan leses i [dokumentasjonen av `sship`](https://rapporteket.github.io/sship/articles/overview.html).
