---
title: "Veiledning"
author: "AblaNor"
date: '`r format(Sys.time(), "%d. %B, %Y")`'
params:
  title: Emty tite
  author: Anon author
  hospitalName: Ukjent sykehus
  tableFormat: html
  reshId: '999999'
---

## Rapporteket for AblaNor `r params$hospitalName`

### Utforsker
Denne siden inneholder en løsning som benytter R-pakken `rpivotTable`. 
Logget inn som lokal koordinator (LC-rolle) kan du laste inn datasett med ditt 
eget sykehus sin aktivitet. Ansatte i registeret (logget inn med SC-rolle) kan
laste inn data med nasjonal aktivitet. Deretter kan disse dataene utforskes 
i tabell-format eller grafisk format.
__Den enkleste måten å bli kjent med verktøyet på er å prøve seg frem!__
 

Det ligger en kort videosnutt som gir et overblikk over hvordan løsningen
fungerer [her](https://i0.wp.com/nicolas.kruchten.com/pivottable/images/animation.gif "Videosnutt rpivotTable").        
Man kan i tillegg finne mer informasjon om pakken på
[hjemmesiden til `rpivotTable`](https://pivottable.js.org/examples/ "Hjemmesiden til rpivotTable"). 

### Kodebok
Dette er et oppslagsverk der man kan se forklaringstekster for alle variablene 
i Utforsker, tabell for tabell. Kodeboken er søkbar. Variabler markert med 
Skjemanavn _utledet_variabel_ betyr at variabelen ikke finnes i selve 
databasen, men er utledet på grunnlag av variabler i databasen. 

### Datadump
Her kan du laste ned tabeller som inneholder ditt lokale sykehus sin aktivitet
fra en valgfri periode i csv- eller xlsx-csv format. 

Tabellen _pros_patient_followup_ inneholder variablene fra basisskjema,
prosedyreskjema og oppfølgingsskjema, samt noen utledete variabler, for alle 
pasienter som har fått utført prosedyre. 

De andre tabellene inneholder alle rådata, det vil si også radene for pasienter
der ingen prosedyre har blitt utført. 

Tabellen _Kodeboken_ inneholder forklaringer til de ulike variablene, 
f.eks. variabletype, variabelnavn og hjelpetekst. 

    
### Månedsrapporter
Månedsrapportene inneholder en oppsummering av aktiviteten for ditt lokale
sykehus det siste året. Du kan laste ned rapporten når det måtte ønskes, eller
du kan få tilsendt rapporten automatisk per e-post (se Abonnement).


### Abonnement
Her kan du administrere dine abonnement på månedsrapportene.  
Du kan selv velge hvor ofte du får dem tilsendt (frekvens) og ønsket format 
(html eller pdf).
